import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { createServer } from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('qa', { recursive: true });
const original = await readFile('index.html', 'utf8');
// Engine hooks are injected only into the test response, never published.
const html = original.replace('\n})();\n</script>', '\nwindow.__engine={game,tick,start,crash,pause,resume,flap,getCanState:()=>({webgl,canVisible,trick,hidden:document.hidden})};\n})();\n</script>');
assert.notEqual(html, original);
const server = createServer((req, res) => { res.writeHead(200, { 'Content-Type': 'text/html' }); res.end(html); });
await new Promise(resolve => server.listen(4173, '127.0.0.1', resolve));
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage(), errors = [], passed = [];
page.on('pageerror', error => errors.push(error.message));
const record = message => { passed.push(message); console.log('PASS:', message); };
const visit = async () => { await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' }); await page.evaluate(() => document.fonts.ready); };
const equalText = async (selector, expected) => assert.equal((await page.locator(selector).textContent()).trim(), expected);
const closeDialog = async () => { await page.keyboard.press('Escape'); await page.waitForTimeout(120); };
const waitTrick = async () => page.waitForFunction(() => !document.querySelector('#flipButton').disabled, null, { timeout: 20000 });
try {
  await visit();
  await page.waitForFunction(() => document.querySelector('#canStatus').textContent.includes('Drag to vibe'), null, { timeout: 20000 });
  assert.equal(await page.locator('#canCanvas').isVisible(), true);
  assert.equal(await page.evaluate(() => THREE.REVISION), '128');
  record('Three.js r128 loads and the WebGL can renders');
  await page.locator('[data-flavor="1"]').click(); await equalText('#calsBadge', '40 Cals');
  assert.match(await page.locator('#flavorNotes').textContent(), /Sun-kissed/);
  await page.locator('[data-flavor="2"]').click(); await equalText('#sugarBadge', '4g Sugar'); await equalText('#calsBadge', '30 Cals');
  await page.locator('#spinButton').click(); await waitTrick();
  await page.locator('#flipButton').click(); await waitTrick();
  await page.locator('[data-flavor="0"]').click();
  record('Flavor colors, nutrition, 360° spin and kickflip controls update without reload');
  await page.screenshot({ path: 'qa/desktop.png', fullPage: true });
  await page.locator('.hero-actions [data-open="packDrawer"]').click();
  assert.equal(await page.locator('#checkoutButton').isDisabled(), true);
  for (let f=0;f<3;f++) for(let i=0;i<4;i++) await page.locator(`[data-plus="${f}"]`).click();
  await equalText('#packCount','12'); await equalText('#subtotal','US$36.00');
  assert.equal(await page.locator('[data-plus="0"]').isDisabled(),true);
  assert.equal(await page.locator('#checkoutButton').isEnabled(),true);
  await page.locator('[data-minus="0"]').click();
  assert.equal(await page.locator('#checkoutButton').isDisabled(),true);
  await equalText('#subtotal','US$33.00');
  await page.locator('[data-plus="0"]').click(); await page.locator('#checkoutButton').click();
  assert.equal(await page.locator('#checkoutModal').isVisible(),true);
  assert.match(await page.locator('#checkoutSummary').textContent(),/12 cans/);
  await page.locator('#editPack').click(); await closeDialog(); await visit(); await equalText('#packCount','12');
  record('Pack caps at 12, subtotal recalculates, checkout unlocks exactly at 12 and pack persists');
  await page.locator('.pack-bar').click(); await page.locator('#resetPack').click(); await equalText('#packCount','0');
  assert.equal(await page.locator('[data-minus="0"]').isDisabled(),true); await closeDialog();
  assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('pack-bar')),true);
  record('Pack cannot go below zero; Escape closes the drawer and restores keyboard focus');
  await page.locator('[data-open="wholesaleModal"]').click();
  await page.locator('#wholesaleForm [type="submit"]').click();
  assert.equal(await page.locator('#wholesaleSuccess').isVisible(),false);
  await page.locator('#business').fill('Demo Cafe'); await page.locator('#email').fill('owner@example.com');
  await page.locator('#businessType').selectOption('Cafe / Restaurant'); await page.locator('#message').fill('A fictional test inquiry.');
  await page.locator('#wholesaleForm [type="submit"]').click();
  assert.equal(await page.locator('#wholesaleSuccess').isVisible(),true);
  assert.match(await page.locator('#wholesalePreview').textContent(),/Demo Cafe/);
  await page.locator('#editInquiry').click(); await closeDialog();
  record('Wholesale form blocks invalid input, previews valid drafts and supports editing');
  for(const [i,region] of ['Singapore','West Coast','East Coast'].entries()){
    await page.locator(`#region-${i}`).click(); assert.equal(await page.locator('.score-row').count(),5);
    assert.equal(await page.locator('#scoreRegion').inputValue(),region);
  }
  await page.locator('#region-0').click(); await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#region-1').getAttribute('aria-selected'),'true');
  record('All regional boards contain 5 seed entries and tabs support keyboard navigation');
  await page.locator('#startGame').click(); await page.keyboard.press('Space');
  assert.equal(await page.evaluate(()=>window.__engine.game.state),'playing');
  await page.keyboard.press('Escape'); assert.equal(await page.locator('#pauseOverlay').isVisible(),true);
  await page.locator('#resumeGame').click();
  await page.evaluate(()=>{
    const {game,tick}=window.__engine; game.y=300;game.vy=0;game.timer=0;
    game.pipes=[{x:63,w:61,center:300,gap:178,passed:false,orb:false}];tick(1/120);
    if(game.orbs!==1||game.total!==5)throw Error('Orb must award exactly 5 points');
    game.pipes=[{x:0,w:61,center:300,gap:178,passed:false,orb:true}];tick(1/120);
    if(game.score!==1||game.total!==6)throw Error('Pair must award exactly 1 point');
    game.y=10;tick(1/120);if(game.state!=='over')throw Error('Ceiling collision');
  });
  await equalText('#finalScore','1');await equalText('#finalOrbs','1');await equalText('#finalTotal','6');await equalText('#bestScore','6');
  record('Flap and pause/resume work; orb +5, straw +1 and ceiling collision are correct');
  await page.locator('#handle').fill('@test_fizzer');await page.locator('#scoreRegion').selectOption('Singapore');await page.locator('#submitScore').click();
  assert.equal(await page.locator('#submitScore').isDisabled(),true);
  assert.equal(await page.locator('#region-0').getAttribute('aria-selected'),'true');
  assert.match(await page.locator('#leaderboardRows').textContent(),/@test_fizzer/);assert.equal(await page.locator('.score-row').count(),6);
  await visit();await equalText('#bestScore','6');assert.match(await page.locator('#leaderboardRows').textContent(),/@test_fizzer/);
  record('Score submission switches region, sorts, prevents duplicates and persists with best score');
  await page.locator('#startGame').click();
  await page.evaluate(()=>{const {game,tick}=window.__engine;game.y=200;game.vy=0;game.pipes=[{x:80,w:61,center:420,gap:178,passed:false,orb:true}];tick(1/120);if(game.state!=='over')throw Error('Straw collision')});
  await page.locator('#replayGame').click();
  await page.evaluate(()=>{const {game,tick}=window.__engine;game.y=570;game.vy=200;tick(1/120);if(game.state!=='over')throw Error('Ground collision')});
  await page.locator('#replayGame').click();await page.locator('.pack-bar').click();
  assert.equal(await page.evaluate(()=>window.__engine.game.state),'paused');await closeDialog();
  await page.locator('#muteButton').click();assert.equal(await page.locator('#muteButton').getAttribute('aria-label'),'Mute game audio');await page.locator('#muteButton').click();
  record('Straw and ground AABB collisions, replay, auto-pause on dialog and audio toggle work');
  await page.locator('#motionToggle').click();assert.equal(await page.evaluate(()=>document.documentElement.classList.contains('motion-off')),true);
  await page.locator('#marqueePause').click();assert.equal(await page.locator('#marqueePause').getAttribute('aria-pressed'),'true');
  record('Ambient motion and ticker can be stopped independently');
  await visit();
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  await writeFile('qa/accessibility.json',JSON.stringify(axe.violations,null,2));
  assert.equal(axe.violations.length,0,JSON.stringify(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))));
  record('Automated axe WCAG 2 A/AA and 2.1 AA checks report no violations');
  await page.locator('.pack-bar').click();
  const dialogAxe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  assert.equal(dialogAxe.violations.length,0,JSON.stringify(dialogAxe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))));await closeDialog();
  record('Open pack dialog passes automated accessibility checks');
  for(const width of [320,375,390,768,1024,1440]){
    await page.setViewportSize({width,height:900});await page.waitForTimeout(150);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`No horizontal overflow at ${width}px`);
  }
  record('No horizontal page overflow at 320, 375, 390, 768, 1024 and 1440px');
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));
  await page.locator('#menuToggle').click();assert.equal(await page.locator('#navLinks').isVisible(),true);
  await page.locator('#navLinks a[href="#flavors"]').click();assert.equal(await page.locator('#menuToggle').getAttribute('aria-expanded'),'false');
  await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(800);await page.screenshot({path:'qa/mobile.png',fullPage:true});
  record('Mobile navigation opens, navigates and closes correctly');
  const fallback=await browser.newContext({viewport:{width:390,height:844}});
  await fallback.route('**/three.min.js',route=>route.abort());
  await fallback.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('Storage blocked')}})});
  const fp=await fallback.newPage();await fp.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
  assert.equal(await fp.locator('#fallbackCan').isVisible(),true);await fp.locator('[data-add="0"]').click();assert.equal(await fp.locator('#packCount').textContent(),'1');
  await fp.locator('[data-flavor="2"]').click();assert.equal(await fp.locator('#fallbackFlavor').textContent(),'ELECTRIC LEMON');await fallback.close();
  record('Blocked Three.js and localStorage degrade gracefully');
  assert.deepEqual(errors,[]);record('No uncaught browser JavaScript errors');
  await writeFile('qa/REPORT.md','# Browser verification\n\nVerified with Chromium / Playwright 1.51.1. Engine hooks are injected into test responses only.\n\n'+passed.map(x=>'- [x] '+x).join('\n')+'\n\nAutomated accessibility checks do not replace manual assistive-technology testing. [Desktop preview](desktop.png) · [Mobile preview](mobile.png).\n');
}catch(error){
  const canState=await page.evaluate(()=>window.__engine?.getCanState()).catch(()=>null);
  await page.screenshot({path:'qa/failure.png',fullPage:true}).catch(()=>{});
  await writeFile('qa/FAILURE.txt',String(error.stack)+'\nCan state: '+JSON.stringify(canState)+'\nPassed: '+passed.join('; ')+'\nBrowser errors: '+errors.join('\n'));
  console.error(error);process.exitCode=1;
}finally{await browser.close();server.close()}
